FROM docker.xuanyuan.me/python:3.11

COPY ssh_key/admin_authorized_keys /home/admin/.ssh/authorized_keys
COPY ssh_key/normalop_authorized_keys /home/normalop/.ssh/authorized_keys
COPY ssh_key/op_authorized_keys /home/op/.ssh/authorized_keys
COPY ssh_key/powerop_authorized_keys /home/powerop/.ssh/authorized_keys

# 设置 APT 源为华为并更新
RUN rm -rf /etc/apt/sources.list.d/* \
    && echo "deb https://mirrors.huaweicloud.com/debian/ bookworm main contrib non-free non-free-firmware" > /etc/apt/sources.list \
    && echo "deb https://mirrors.huaweicloud.com/debian/ bookworm-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list \
    && echo "deb https://mirrors.huaweicloud.com/debian/ bookworm-backports main contrib non-free non-free-firmware" >> /etc/apt/sources.list \
    && echo "deb https://mirrors.huaweicloud.com/debian-security bookworm-security main contrib non-free non-free-firmware" >> /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y openssh-server supervisor sudo \
    && ssh-keygen -A \
    && mkdir -p /run/sshd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY rootfs/  /

RUN groupadd Domain_AutonomyUser && \
    groupadd Domain_PowerUser && \
    groupadd -g 2000 storage-admin && \
    useradd -s /bin/bash -M powerop -G Domain_AutonomyUser && \
    useradd -s /bin/bash -m admin && \
    useradd -s /bin/bash -m normalop && \
    useradd -s /bin/bash -m deploy && \
    chown -R powerop:powerop /home/powerop/ && \
    chown -R admin:admin /home/admin/ && \
    chown -R normalop:normalop /home/normalop/ && \
    chown -R deploy:deploy /home/deploy/ && \
    chmod 600 /home/op/.ssh/authorized_keys && \
    chmod 600 /home/powerop/.ssh/authorized_keys && \
    chmod 600 /home/normalop/.ssh/authorized_keys && \
    chmod 600 /home/admin/.ssh/authorized_keys && \
    chmod +x /opt/container/entrypoint.sh && \
    chmod 644 /etc/sudoers && \
    apt-get install -y tzdata && \
    rm -f /etc/localtime && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    mkdir -p /mnt/mesos/sandbox /opt/logs && \
    chown -R deploy:deploy /opt/logs && \
    ln -s /mnt/mesos/sandbox/SimpleHTTPServer.log /opt/logs

WORKDIR /opt/app

# 设置 pip 使用华为源并安装依赖
COPY ./requirements_server.txt ./requirements.txt

RUN python -m pip config set global.index-url https://mirrors.huaweicloud.com/repository/pypi/simple \
    && pip install --no-cache-dir -r ./requirements.txt \
    && python -m pip cache purge

# 设置环境变量
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8
ENV PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app

# 拷贝代码
COPY ./build /ai_assistant
COPY ./src ./src
COPY ./app.py ./app.py
RUN mkdir -p /var/crawl

ENTRYPOINT /opt/container/entrypoint.sh
