FROM docker.xuanyuan.me/python:3.11

# 设置工作目录
WORKDIR /app

# 设置 APT 源为华为并更新
RUN rm -rf /etc/apt/sources.list.d/* \
    && echo "deb https://mirrors.huaweicloud.com/debian/ bookworm main contrib non-free non-free-firmware" > /etc/apt/sources.list \
    && echo "deb https://mirrors.huaweicloud.com/debian/ bookworm-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list \
    && echo "deb https://mirrors.huaweicloud.com/debian/ bookworm-backports main contrib non-free non-free-firmware" >> /etc/apt/sources.list \
    && echo "deb https://mirrors.huaweicloud.com/debian-security bookworm-security main contrib non-free non-free-firmware" >> /etc/apt/sources.list \
    && apt-get update \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# 设置 pip 使用华为源并安装依赖
COPY ./requirements_server.txt ./requirements.txt

RUN python -m pip config set global.index-url https://mirrors.huaweicloud.com/repository/pypi/simple \
    && pip install --no-cache-dir -r /app/requirements.txt \
    && pip install --no-cache-dir textract python-magic \
    && python -m pip cache purge

# 设置环境变量
ENV PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app

# 拷贝代码
COPY ./build /ai_assistant
COPY ./src ./src
COPY ./app.py ./app.py

ENTRYPOINT ["python", "/app/app.py"]

