FROM docker.xuanyuan.me/python:3.11
RUN cat /etc/os-release

# 替换 Debian 12 apt 源为华为
RUN rm -rf /etc/apt/sources.list.d/* \
    && echo "deb https://mirrors.huaweicloud.com/debian/ bookworm main contrib non-free non-free-firmware" > /etc/apt/sources.list \
    && echo "deb https://mirrors.huaweicloud.com/debian/ bookworm-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list \
    && echo "deb https://mirrors.huaweicloud.com/debian/ bookworm-backports main contrib non-free non-free-firmware" >> /etc/apt/sources.list \
    && echo "deb https://mirrors.huaweicloud.com/debian-security bookworm-security main contrib non-free non-free-firmware" >> /etc/apt/sources.list \
    && apt-get update

# 设置 pip 使用华为源，并安装依赖
COPY ./requirements.txt /app/requirements.txt

RUN python -m pip config set global.index-url https://mirrors.huaweicloud.com/repository/pypi/simple && \
    pip install --no-cache-dir -r /app/requirements.txt && \
    pip install --no-cache-dir textract python-magic

# 设置工作目录
WORKDIR /app

# 设置环境变量
ENV PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app

# 拷贝代码
COPY ./src ./src
COPY ./app.py ./app.py
COPY ./vector_store /vector_store
COPY ./onnx_models /onnx_models

CMD python /app/app.py
